disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - type_name
  - identifier_name
  - function_parameter_count

# opt_in_rules: # some rules are only opt-in
# included: # paths to include during linting. `--path` is ignored if present.
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods

file_length:
  - 600

line_length:
  - 300

large_tuple:
  - 32

type_body_length:
  - 450
  - 700

force_cast: warning
force_try: warning
cyclomatic_complexity:
  ignores_case_statements: true