//
//  ViewGymsOnMapPresenter.swift
//  Bouldering
//
//  Created by Po Sam on 23/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymsOnMapPresentationLogic {
    func display(gyms: [Gym])
}

class ViewGymsOnMapPresenter: ViewGymsOnMapPresentationLogic {
    
    weak var viewController: ViewGymsOnMapDisplayLogic?
    
    // MARK: Do something
    
    func display(gyms: [Gym]) {
        DispatchQueue.main.async {
            let viewModels = gyms.map {
                GymPoiViewModel(name: $0.name,
                                latitude: $0.coordinates.latitude,
                                longitude: $0.coordinates.longitude)
            }
            
            self.viewController?.display(viewModels: viewModels)
        }
    }
}
