//
//  ViewGymsOnMapInteractor.swift
//  Bouldering
//
//  Created by Po Sam on 23/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymsOnMapBusinessLogic {
}

protocol ViewGymsOnMapDataStore {
}

class ViewGymsOnMapInteractor: ViewGymsOnMapBusinessLogic, ViewGymsOnMapDataStore {
    
    var presenter: ViewGymsOnMapPresentationLogic?
    
    // MARK: Do something
    
}
