//
//  ViewGymsOnMapRouter.swift
//  Bouldering
//
//  Created by Po Sam on 23/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymsOnMapRoutingLogic {
    func navigateToDetails()
    
    func prepare(for segue: UIStoryboardSegue, sender: Any?)
}

protocol ViewGymsOnMapDataPassing {
    var dataStore: ViewGymsOnMapDataStore? { get }
}

class ViewGymsOnMapRouter: NSObject, ViewGymsOnMapRoutingLogic, ViewGymsOnMapDataPassing {
    
    weak var viewController: ViewGymsOnMapViewController?
    var dataStore: ViewGymsOnMapDataStore?
    
    // MARK: Routing
    
    // MARK: Navigation
    
    func navigateToDetails() {
        viewController?.navigate(to: .gymDetails)
    }
    
    // MARK: Passing data
    
    func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let viewGymDetailsViewController = segue.destination as? ViewGymDetailsViewController {
            if let selectedGym = dataStore?.selectedGym {
                viewGymDetailsViewController.interactor?.set(gym: selectedGym)
            }
        }
    }
    
}
