//
//  ViewGymsOnMapRouter.swift
//  Bouldering
//
//  Created by Po Sam on 23/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymsOnMapRoutingLogic {
}

protocol ViewGymsOnMapDataPassing {
    var dataStore: ViewGymsOnMapDataStore? { get }
}

class ViewGymsOnMapRouter: NSObject, ViewGymsOnMapRoutingLogic, ViewGymsOnMapDataPassing {
    
    weak var viewController: ViewGymsOnMapViewController?
    var dataStore: ViewGymsOnMapDataStore?
    
    // MARK: Routing
    
    // MARK: Navigation
    
    // MARK: Passing data
    
}
