//
//  ViewGymDetailsRouter.swift
//  Bouldering
//
//  Created by Po Sam on 26/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ViewGymDetailsRoutingLogic { }

protocol ViewGymDetailsDataPassing {
    var dataStore: ViewGymDetailsDataStore? { get }
}

class ViewGymDetailsRouter: NSObject, ViewGymDetailsRoutingLogic, ViewGymDetailsDataPassing {
    
    weak var viewController: ViewGymDetailsViewController?
    var dataStore: ViewGymDetailsDataStore?
    
    // MARK: Routing
    
    // MARK: Navigation
    
    // MARK: Passing data
    
}
