//
//  ViewGymDetailsInteractor.swift
//  Bouldering
//
//  Created by Po Sam on 26/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymDetailsBusinessLogic {
    func set(gym: Gym)
    func start()
}

protocol ViewGymDetailsDataStore {
    var gym: Gym? { get }
}

class ViewGymDetailsInteractor: ViewGymDetailsBusinessLogic, ViewGymDetailsDataStore {
    
    var presenter: ViewGymDetailsPresentationLogic?
    private(set) var gym: Gym?
    
    // MARK: Do something
    
    func set(gym: Gym) {
        self.gym = gym
    }
    
    func start() {
        guard let gym = self.gym else { return }
        
        presenter?.display(gym: gym)
    }
}
