//
//  ViewGymDetailsPresenter.swift
//  Bouldering
//
//  Created by Po Sam on 26/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymDetailsPresentationLogic {
    func display(gym: Gym)
}

class ViewGymDetailsPresenter: ViewGymDetailsPresentationLogic {
    
    weak var viewController: ViewGymDetailsDisplayLogic?
    
    // MARK: Do something
    
    func display(gym: Gym) {
        let viewModel = GymDetailsViewModel(gym: gym)
        self.viewController?.display(viewModel: viewModel)
    }
}
