//
//  ViewGymDetailsInteractor.swift
//  Bouldering
//
//  Created by Po Sam on 26/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymDetailsBusinessLogic { }

protocol ViewGymDetailsDataStore { }

class ViewGymDetailsInteractor: ViewGymDetailsBusinessLogic, ViewGymDetailsDataStore {
    
    var presenter: ViewGymDetailsPresentationLogic?
    
    // MARK: Do something
    
}
