//
//  ViewGymDetailsInteractor.swift
//  Bouldering
//
//  Created by Po Sam on 26/12/2017.
//  Copyright (c) 2017 Mobairu. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ViewGymDetailsBusinessLogic {
    func set(gym: Gym)
    func start()
    
    func call()
    func mail()
    func visitWebsite()
}

protocol ViewGymDetailsDataStore {
    var gym: Gym? { get }
}

class ViewGymDetailsInteractor: ViewGymDetailsBusinessLogic, ViewGymDetailsDataStore {
    
    var presenter: ViewGymDetailsPresentationLogic?
    private(set) var gym: Gym?
    
    // MARK: Do something
    
    func set(gym: Gym) {
        self.gym = gym
    }
    
    func start() {
        guard let gym = self.gym else { return }
        
        presenter?.display(gym: gym)
    }
    
    func call() {
        guard let phone = gym?.contacts.phone,
            let url = URL(string: "tel://\(phone)"),
            UIApplication.shared.canOpenURL(url) else { return }
        
        UIApplication.shared.open(url)
    }
    
    func mail() {
        guard let email = gym?.contacts.email,
            let url = URL(string: "mailto://\(email)"),
            UIApplication.shared.canOpenURL(url) else { return }
        
        UIApplication.shared.open(url)
    }
    
    func visitWebsite() {
        guard let website = gym?.contacts.website,
            let url = URL(string: website),
            UIApplication.shared.canOpenURL(url) else { return }
        
        UIApplication.shared.open(url)
    }
}
